### ISSUE TITLE
Units speaking in Farsi?

### ISSUE THREAD

**Issue by RumHam3d** [BlueHarvestInteractive/Imperial-Assault#16]
Both OPFOR and BLUEFOR are speaking in Farsi

**Comment by pomigit** [comment]
This isnt so much a bug, Its just that our units are inherriting the default voice profile for OPFOR. It will be replaced with the one Maxx is making in package 2

**Comment by pomigit** [comment]
Resolved. Added Stormtrooper profile which gets rid of thsi
