### ISSUE TITLE
Non scouts cannot throw thermal detonator

### ISSUE THREAD

**Issue by RumHam3d** [BlueHarvestInteractive/Imperial-Assault#19]
Vanilla ARMA 3 characters cannot throw the thermal detonator (ie. if you are eg. a NATO soldier and pick up a thermal detonator, you cannot select it in your grenades list)

**Comment by pomigit** [comment]
Not a bug. Its a design decision, I deliberately limited the use of thermal detonators to our units. 

Will keep an eye on this. If it causes a lot of confusion I can easily change it

**Comment by pomigit** [comment]
No change to be made. Throw and Put class names modified to be specific to be Imp_Throw and Imp_Put. These will only be used by imperials. Once we add rebels they will use standard Put and Throw
