### ISSUE TITLE
Uniform equipping issue

### ISSUE THREAD

**Issue by RumHam3d** [BlueHarvestInteractive/Imperial-Assault#20]
Cant equip the uniform if you arent a scout. Weapon, Helmet and body armour works fine though.

**Comment by pomigit** [comment]
Low priority item. Need to test whether this is just related to different sides being unable to wear opposite sides uniforms

**Comment by pomigit** [comment]
Issue is due there being two versions of the compression suit. one for blufor and one for opfor. If either side tries to equip then it will not work. No change required
