### ISSUE TITLE
User created mission not working on dedicated server

### ISSUE THREAD

**Issue by RumHam3d** [BlueHarvestInteractive/Imperial-Assault#21]
Issue reported on BI Forum:

I made a SC type mission for it and I wanted to put that on my server.
Now my problem is that the server won't launch the mission.
Code:
11:14:23 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
bh_swia_pistols
11:14:23 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
bh_swia_weapons_explosives
It works fine when I localhost it, a friend can join and play, just not for the dedicated server.
I tried downloading it from PWS and armaholic but neither works.

**Comment by pomigit** [comment]
I'll leave this one for you to resolve @RumHam3d
