### ISSUE TITLE
Speeder bike w/unit not listed under BLUFOR

### ISSUE THREAD

**Issue by RumHam3d** [BlueHarvestInteractive/Imperial-Assault#6]
The speeder bike is not listed under blufor and cant be spawned with a blufor unit on it. Right now you must spawn an empty bike and make a unit enter it. This is not a problem on the Opfor side.

**Comment by pomigit** [comment]
I'm inclined to leave this as is. The blue and red scouts are really only meant to be temporary until we have rebels. I never intended to have any galactic units under BLUFOR.

Thoughts?

**Comment by pomigit** [comment]
No plans to add. scout blufor version will be removed in pack 3
